services:
    - type: web
      name: triviaquest-finalproject
      env: python
      region: ohio
      buildCommand: "./render_build.sh"
      startCommand: "gunicorn wsgi --chdir ./src/"
      plan: free
      numInstances: 1
      envVars:
          - key: VITE_BASENAME
            value: /
          - key: FLASK_APP
            value: src/app.py
          - key: FLASK_DEBUG
            value: 0
          - key: JWT_SECRET_KEY
            generateValue: true
          - key: PYTHON_VERSION
            value: 3.10.6
          - key: DATABASE_URL
            fromDatabase:
                name: triviaquest-db
                property: connectionString

databases:
    - name: triviaquest-db
      region: ohio
      ipAllowList: []
      plan: free